### ISSUE TITLE
Fix telemetry to not stop deployments when a current PID exists

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#124]
**Describe the bug**
If a PID exists in a region, it stops the deployment and gives this error:

{"code": "InvalidDeploymentLocation", "message": "Invalid deployment location 'usgovvirginia'. The deployment 'pid-66764817-8a40-4c5a-a9ea-dee657961d13' already exists in location 'usgovarizona'."}

**To Reproduce**

1. Run platform hub/3 spoke
2. See the error

**Expected behavior**
Deployment is supposed to work without this error

**Software versions used:**

- Azure CLI version [v2.23.0]
- Azure Bicep version [v0.6.8]

**Comment by matross-ghes** [comment]
Need to fix in management groups
