### ISSUE TITLE
Microsoft Defender for Cloud defender plan configuration needs to be serial

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#135]
**Is your feature request related to a problem? Please describe.**
For conflicts not to arise in the pricing for Defender, I would put a batchSize(1) on the pricing resource.

**Describe the solution you'd like**
batchSize(1)
resource pricingTiers 'Microsoft.Security/pricings@2018-06-01' = [for (pricing, index) in pricings: {
  name: pricing.name
  properties: {
    pricingTier: pricing.pricingTier
  }
}]

**Comment by jftl6y** [comment]
Fixed in bicep
