### ISSUE TITLE
The Virtual Networks do not send Diagnostic Data to the Log Analytics Workspace and Storage Account

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#145]
**Describe the bug**
The code sets the diagnostic settings on the Virtual Network, but it never gets deployed.

**To Reproduce**

1. Deploy the Hub Spoke Platform

**Expected behavior**
The Virtual Network should have a Diagnostics Setting to send logs and metrics to the Log Analytics Workspace.

**Screenshots**
![image](https://user-images.githubusercontent.com/5787207/197896499-9ecfe558-a5ab-4f6f-9b90-a2f2339d0caa.png)

**Additional context**
The code should deploy diagnostic settings to every Virtual Network.

// HUB
anoa.lz.hub.network.bicep

// HUB ACTIVITY LOGGING - VDMS

module hubSubscriptionActivityLogging '../../../Modules/Microsoft.Insights/diagnosticSettings/az.insights.diagnostic.setting.bicep' = {
  name: 'deploy-activity-logs-hub-${parLocation}-${parDeploymentNameSuffix}'
  scope: subscription(parHubSubscriptionId)
  params: {
    name: 'log-hub-sub-activity-to-${parLogAnalyticsWorkspaceName}'
    diagnosticWorkspaceId: parLogAnalyticsWorkspaceResourceId
    diagnosticLogCategoriesToEnable: [
      'Administrative'
      'Security'
      'ServiceHealth'
      'Alert'
      'Recommendation'
      'Policy'
      'Autoscale'
      'ResourceHealth'
    ]
    diagnosticMetricCategoriesToEnable: []
  }
  dependsOn: [
    modHubVirtualNetwork
    modHubLogStorage
  ]
}
Cloud (public, Azure Government, etc.):

**Comment by jftl6y** [comment]
Need to understand if this is a bug with regards to Virtual Network resource types or if it would apply to setting diagnostic settings for other resource types (VMs, Application Gateways, etc.).

**Comment by jftl6y** [comment]
OBE - moving to assignment via policy.
