### ISSUE TITLE
Broken Link in NoOps Accelerator - Bicep Modules Readme file

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#148]
## Description
There is a broken link in https://github.com/Azure/NoOpsAccelerator/blob/main/src/bicep/readme.md
## Steps to Reproduce

1.  navigate to src/bicep/README.md
2.  Select the "README at the root of the folder" link under the **Architecture wiki page** 

## Expected behavior

The Architecture wiki page does not exist, the link should be deleted

## Actual behavior

404 Not Found

**Comment by jftl6y** [comment]
OBE
