### ISSUE TITLE
NEED TESTERS

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#157]
If you want to help us user-test the Enclave, Platform, and Workload modules of the NoOps Accelerator, please comment below.

Part of being a tester is that you will need to follow the readme for each Enclave, Platform, and Workload deploy steps.

If bugs are found, we need you to add a [bug issue](https://github.com/Azure/NoOpsAccelerator/issues/new?assignees=&labels=needs-triage&template=bug_report.md&title=).  Nothing is off the table, if you see heading wrong, typos, deploy steps that are missing info or wrong, please add in a bug issue for every one.

if you can fix the bug, please ensure you are updating PR and the bug issues.

**Comment by wtomaz808** [comment]
I am down to help/assist with testing/reporting bugs..holla..

**Comment by jrspinella** [comment]
@wtomaz808 Roger, I will add you to the scrum meeting when it gets started
