### ISSUE TITLE
Broken Link in Overlays: NoOps Accelerator - Roles Readme file

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#158]
## Description
There is a broken link in https://github.com/Azure/NoOpsAccelerator/blob/main/src/bicep/overlays/roles/readme.md

## Steps to Reproduce

1.  navigate to src/bicep/overlays/roles/README.md
2.  Select the "README at the root of the folder" link under the **Example Output in Azure** sub-heading

## Expected behavior

Expect to be Example Output in Azure of Management Groups

## Actual behavior

404 Not Found

**Comment by sstjean** [comment]
OBE
