### ISSUE TITLE
Missing Link in Overlays: NoOps Accelerator - Application Gateway Readme file

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#159]
## Description
There is a broken link in https://github.com/Azure/NoOpsAccelerator/blob/main/src/bicep/overlays/management-services/applicationGateway/readme.md
## Steps to Reproduce

1.  navigate to src/bicep/overlays/management-services/applicationGateway/README.md
2.  Select the "README at the root of the folder" link under the **Example Output in Azure** sub-heading

## Expected behavior

Expect to be Example Output in Azure of the Application Gateway

## Actual behavior

404 Not Found or missing

**Comment by sstjean** [comment]
Overtaken by events
