### ISSUE TITLE
Missing Link in Overlays: NoOps Accelerator - Automation Account Readme file

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#160]
## Description
There is a broken link in https://github.com/Azure/NoOpsAccelerator/blob/main/src/bicep/overlays/management-services/automation/readme.md

## Steps to Reproduce

1.  navigate to src/bicep/overlays/management-services/automation/README.md
2.  Select the "README at the root of the folder" link under the **Extending the Overlay** sub-heading

## Expected behavior

Expect to be directed to the AzResources Automation Account: /src/bicep/azresources/Modules/Microsoft.Automation/automationAccounts/readme.md

## Actual behavior

404 Not Found or missing link

**Comment by sstjean** [comment]
Overtaken by events
