### ISSUE TITLE
Opt-in for AllMetrics diagnostic settings

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#172]
## Benefit/Result/Outcome

The Diagnostics Setting for `AllMetrics` is verbose, costly, and not always necessary for SCCA compliance. Instead of being turned on by default, we can make this an opt-in decision.

## Description

The Diagnostic Settings resources are currently created for the firewall, the firewall Public IP addresses, and all network security groups. Update these diagnostic settings resources with `metrics` collections that by default do not configure the `AllMetrics` category, but given a boolean parameter, include that `AllMetrics` category.

## Acceptance Criteria

- The `AllMetrics` diagnostic setting is not enabled by default on the firewall, public IP addresses, and network security groups.
- The firewall, public IP, and network security groups have separate boolean parameters that default to false, which can be overridden to enable `AllMetrics` on any of the resource types listed above, i.e., three boolean parameters control their respective `AllMetrics` settings.
- The parameters are available in Bicep.

**Comment by jrspinella** [comment]
related to issue #134

**Comment by jftl6y** [comment]
AllMetrics is not typically enabled for customers in production. Customer can modify if needed.
