### ISSUE TITLE
Disable metrics in diagnostic settings for AKS through Policy

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#176]
**Describe the bug**
AKS metrics should not be sent through diagnostic settings to Log Analytics Workspace. Metrics will be collected through container insights (if required).

The built-in policy (/providers/Microsoft.Authorization/policyDefinitions/6c66c325-74c8-42fd-a286-a74b0e2939d8) enables metrics automatically and we need to disable as part of Custom - Logging Governance Initiative policy set.

**Additional Context**
Could be solved by using AllMetrics parameter in Custom - Logging Governance Initiative policy set:

```
logAnalytics: {
            value: '[parameters(\'logAnalytics\')]'
          }
          AllMetrics: {
            value: 'False'
          }
        }
      }
```

**Comment by jftl6y** [comment]
Need to have a wider conversation about logging governance issues before moving forward.
