### ISSUE TITLE
Create a Deployment Scenarios folder

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#202]
We need a Deployment Scenarios folder. This folder would have all the deployment scenarios examples for the accelerator. This way, it would be easier for:

1. the user of the accelerator could look at one folder to find deployment scenarios examples.
2. This would condense the accelerator to make it more framework focused.
3. We can call out certain deployment scenarios in our docs and readmes.

**Comment by jftl6y** [comment]
OBE - now Examples folder
