### ISSUE TITLE
Create an Architecture Overview for the accelerator

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#205]
This overview describes how to build a reference implementation with the Accelerator. The purpose of the reference implementation is to guide Public Sector customers on building Mission Enclaves in their Azure environment.

It would be broken down into:

1. Key Decisions -  outlines the key decisions each customer must consider as part of adopting Azure.
2. Management Groups
4. RBAC
5. Policy - common use cases for Azure Policy include implementing governance
6. Enclave
7. Platforms
8. Logging
9. Tagging
10. Workload(s)
11. Automation

**Comment by jftl6y** [comment]
OBE
