### ISSUE TITLE
Create an enclave like an MLZ with a private AKS cluster

### ISSUE THREAD

**Issue by sstjean** [Azure/NoOpsAccelerator#21]
# Enclave Request
_An Enclave is composed of a Landing Zone and one or more valuable workloads.  This request is for the team to pull together these components and shared services workloads (optional) into a single deployment script._

### Please describe the need/value of this enclave
Many US DoD customers need a place to run their production container workloads.  The landing zone must be SCCA-compliant and support Impact Level 4 data.  
 
### What Landing Zone does it need?
SCCA-Compliant hub and three spoke (MLZ-equivalent) Landing Zone 
US DoD IL4 policy set 

### What goes into Shared Services (if anything)?
None.

### Which Workloads does it contain?
AKS cluster with an internal ingress controller attached to the LZ spoke VNet (peered to the hub VNet) with a public IP on the firewall that sends traffic to the AKS cluster ingress.

**Comment by jrspinella** [comment]
The enclave is complete and tested
