### ISSUE TITLE
Deployment Error: Required property 'type' not found in JSON

### ISSUE THREAD

**Issue by mwdarab** [Azure/NoOpsAccelerator#218]
**Describe the bug**
When I execute the "az deployment sub create" command, I get an error stating "Required property 'type' not found in JSON"

**To Reproduce**

1. Clone the repot and change to directory C:\anoa\NoOpsAccelerator\src\bicep\platforms\lz-platform-scca-hub-3spoke
2. I put my Subscription ID in the deploy.parameters.json file, and save it
3. I execute the following in VS Code terminal (PowerShell):

az deployment sub create --name deploy-hub3spoke-network --location EastUS --template-file deploy.bicep  --parameters @parameters/deploy.parameters.json

4. See below error:

{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"InvalidTemplate\\\",\\r\\n    \\\"message\\\": \\\"Deployment template parse failed: 'Required property 'type' not found in JSON. Path ''.'.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}

**Expected behavior**
I expected this to deploy successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/33947782/206938963-0909a762-5935-41ae-af70-635a26ae3624.png)

**Desktop:**

- OS: Windows 11
- Browser: MS Edge
- Version: 108.0.1462.46 (Official build) (64-bit)

**Software versions used:**

- Azure CLI: v2.24.0
- Azure Bicep: v0.13.1

**Comment by jrspinella** [comment]
Yes, This seems to be a schema problem, as the build ARM JSON is seeing validation errors. I currently have submitted a bug to the AZ bicep team.

**Comment by OutKa5t** [comment]
Here is the problem https://github.com/Azure/NoOpsAccelerator/issues/226

**Comment by jrspinella** [comment]
This is fixed by PR: #227
