### ISSUE TITLE
az.data.storage errors on deployment

### ISSUE THREAD

**Issue by OutKa5t** [Azure/NoOpsAccelerator#226]
**Describe the bug**
A recent change to the way in which the object for the variable 'identity' is built up is causing deployment to fail with an obscure error of:
`"Deployment template parse failed: 'Required property 'type' not found in JSON. Path ''.'.`

See change at https://github.com/Azure/NoOpsAccelerator/commit/5e67563af66a80bc75eba3353b90a990fd1bc25d#diff-1e1103bfc4b0d0e28dbf18a60a8ba947c85028f47257c73cda0c300a9951e061L173-L174

Checked a revert of the change builds and deploys fine successfully. 

` az bicep build --file .\az.data.storage.bicep --stdout`

**To Reproduce**

Either attempt to deploy the bicep file in isolation:
`az deployment group create --resource-group 'test-anoa' --template-file '.\az.data.storage.bicep'`

or as part of a bigger deployment for example a hub3spoke:
`az deployment sub create --name 'deploy-hub3spoke-network' --subscription $context.Subscription.Id --template-file 'deploy.bicep' --location $location --parameters '@parameters/deploy.parameters.json' --only-show-errors`

both will call the fail when the deployment of az.data.storage.bicep with the error in the description. 

**Expected behavior**
Deployment is successful and a storage account is created.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows

**Software versions used:**

{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
and 
{
  "azure-cli": "2.43.0",
  "azure-cli-core": "2.43.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5"
  }
}

Bicep CLI version 0.13.1 (e3ac80d678)

**Additional context**

**Comment by OutKa5t** [comment]
@jftl6y FYI.

**Comment by jrspinella** [comment]
I merged your change, David! Thanks for fixing the error!

closes #227
