### ISSUE TITLE
Full Scope Enclave Deployment

### ISSUE THREAD

**Issue by STG5326** [Azure/NoOpsAccelerator#60]
Full enclave deployment once the first one is determined along with what's deployed in the enclave.

**Comment by sstjean** [comment]
This looks like a test that @matross-ghes did this week.  Do you want to take ownership of this Matt?

**Comment by matross-ghes** [comment]
@sstjean You bet, got it!

**Comment by jrspinella** [comment]
This looks like this is related to #128
